import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import  SmoothScroll  from "@/app/components/SmoothScroll";
import Reveal from "@/app/components/Reveal";
import { WalletProvider } from "@/app/providers/WalletProviders";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
           <WalletProvider>
          <SmoothScroll>
            <Reveal selector=".reveal">
              {children}
            </Reveal>
          </SmoothScroll>
        </WalletProvider>
      </body>
    </html>
  );
}
